### PR TITLE
Upgraded serialport to v9.0.2

### PR DESCRIPTION
**Pull request by MarcoTomasRodriguez**
Solves #16

### CODE REVIEW

**Comment by 101100** [comment]
Thanks for the PR.  I'll release this as `v5.0.0` since it changes the major version of `serialport`.  After that, can you confirm it is working for you?

**Comment by 101100** [comment]
This has been published as `v5.0.0`, please let me know if you run into any issues.

**Comment by MarcoTomasRodriguez** [comment]
Sure, I will test the devices with v.5.0.0 and notify if any error occurs. Thank you.

**Comment by brajchit** [comment]
I found a error with v5.0, when send and receibe data from remote xbee:

```
/home/pi/Templates/gw-companyDemo-fincaDemo1/bluegateway/node_modules/xbee-api/lib/xbee-api.js:220
        var err = new Error("Checksum Mismatch " + JSON.stringify(S));
                  ^

Error: Checksum Mismatch {"buffer":{"type":"Buffer","data":[126,0,38,144,0,123,4,108,87,127,236,66,89,148,67,142,83,53,170,156,197,79,82,93,186,140,255,15,142,20,31,130,80,255,15,170,26,56,131,0,155,191,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"offset":42,"length":38,"total":4061,"checksum":191,"b":191,"escape_next":false,"waiting":false}
    at XBeeAPI.parseRaw (/home/pi/Templates/gw-companyDemo-fincaDemo1/bluegateway/node_modules/xbee-api/lib/xbee-api.js:220:19)
    at Transform.XBeeAPI.parser._transform (/home/pi/Templates/gw-companyDemo-fincaDemo1/bluegateway/node_modules/xbee-api/lib/xbee-api.js:48:19)
    at Transform._write (node:internal/streams/transform:184:23)
    at writeOrBuffer (node:internal/streams/writable:388:12)
    at Transform.Writable.write (node:internal/streams/writable:333:10)
    at SerialPort.ondata (node:internal/streams/readable:715:22)
    at SerialPort.emit (node:events:329:20)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:279:9)
    at SerialPort.Readable.push (node:internal/streams/readable:218:10)
Emitted 'error' event on XBeeAPI instance at:
    at XBeeAPI.parseRaw (/home/pi/Templates/gw-companyDemo-fincaDemo1/bluegateway/node_modules/xbee-api/lib/xbee-api.js:221:14)
    at Transform.XBeeAPI.parser._transform (/home/pi/Templates/gw-companyDemo-fincaDemo1/bluegateway/node_modules/xbee-api/lib/xbee-api.js:48:19)
    [... lines matching original stack trace ...]
    at SerialPort.Readable.push (node:internal/streams/readable:218:10)
```

This occurs sometimes, when making requests in group(loop) to remote Xbees and they respond:
Raspberry Pi OS (Linux v5.4)
NVM v0.37
  Nodejs v15.2.1

**Pull request merged**
