### PR TITLE
Update from RxJS v4 to RxJS v6

### PR DESCRIPTION
**Pull request by bruxillensis**

### CODE REVIEW

**Comment by bruxillensis** [comment]
Yarn is failing node 0.x versions. Can support for NodeJS 0.x be dropped?

**Comment by 101100** [comment]
@bpoulse Yeah, feel free to drop `0.x`.  While you are at it, can you please add v8 and v10?  I'll give the code a more thorough look shortly.  I think this should be released as version 4 so older projects won't be affected.

**Comment by bruxillensis** [comment]
Removed node 0.x and added 8 & 10. Serialport needed an update to v6 and I resorted to using npm instead of yarn as it was creating multiple issues with CI and has become somewhat unnecessary. Let me know if these changes are ok.

**Comment by 101100** [comment]
@bpoulse Thanks for the updates!  I pushed one more commit because I still like using yarn, personally.  I also updated a few more dependencies and removed `ramda` to eliminate another dependency.

**Comment by 101100** [comment]
OK, this is published as 4.0.0  Please let me know if you have any problems.

**Pull request merged**
